#!/usr/bin/env python3
"""Generate exact source links for organization Python automation."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "python-api.md"
HEADER = "<!-- Generated by scripts/generate-source-reference.py; do not edit. -->\n\n"


def humanize(value: str) -> str:
    """Convert a Python identifier into a readable responsibility phrase."""
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value.lstrip("_"))
    return value.replace("_", " ").strip().lower() or "source contract"


def summary(node: ast.AST, name: str) -> str:
    """Return the declaration's first docstring sentence or a stable fallback."""
    doc = ast.get_docstring(node, clean=True)
    if doc:
        return re.sub(r"\s+", " ", doc.split("\n", 1)[0]).replace("|", "\\|")
    return f"Implements {humanize(name)} for organization documentation automation."


def signature(lines: list[str], line: int, name: str) -> str:
    """Extract and Markdown-escape the declaration's opening source line."""
    source = lines[line - 1].strip() if line <= len(lines) else name
    return re.sub(r"\s+", " ", source).replace("|", "\\|").replace("`", "&#96;")


def declarations() -> list[dict]:
    """Collect classes and functions from organization automation scripts."""
    rows = []
    for path in sorted((ROOT / "scripts").glob("*.py")):
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        tree = ast.parse(text)
        relative = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            rows.append({
                "kind": kind,
                "name": node.name,
                "path": relative,
                "line": int(node.lineno),
                "signature": signature(lines, int(node.lineno), node.name),
                "summary": summary(node, node.name),
            })
    return sorted(rows, key=lambda row: (row["path"], row["line"], row["name"]))


def render() -> str:
    """Render the deterministic exact-line Python source reference."""
    rows = declarations()
    table = [
        "| Kind | Declaration | Responsibility | Source |",
        "|---|---|---|---|",
    ]
    for row in rows:
        target = f"../../{row['path']}#L{row['line']}"
        source = f"[`{row['path']}:{row['line']}`](<{target}>)"
        table.append(
            f"| {row['kind']} | `{row['signature']}` | {row['summary']} | {source} |"
        )
    return (
        HEADER
        + "# Organization Automation Python API\n\n"
        + f"Source-backed reference for **{len(rows)} declarations** across "
        + f"**{len({row['path'] for row in rows})} automation files**.\n\n"
        + "\n".join(table)
        + "\n"
    )


def main() -> int:
    """Write the reference or fail when checked-in output has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"generated reference is stale: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("organization source reference: PASS")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
